### ISSUE TITLE
Wrong DCC min and max timing?

### ISSUE THREAD

**Issue by rkreienbuehl** [bicknell/rpi-dcc-decoder#1]
Hi
I tried to use your code to decode DCC on my model railroad. Your code is well documented, but what I don't understand is the timing for the DCC min and max
```
#define TICKS_MIN_DCC_ONE   12
#define TICKS_MAX_DCC_ONE   38
#define TICKS_MIN_DCC_ZERO  68
#define TICKS_MAX_DCC_ZERO 150
```

Has NMRA DCC other timings than OpenDCC? As defined in OpenDCC, a one has 58microseconds and a zero 116 microseconds.
[OpenDCC Protocol](https://www.opendcc.de/info/dcc/dcc.html)

Thanks

Kind regards

**Comment by bicknell** [comment]
The units are timer “ticks”, which are not exactly microseconds, and also have some amount of jitter.

Additionally, the DCC systems I have tested against are not always perfectly spec compliant. They sometimes have timings that are just a bit shorter or longer than the spec.

These values were determined experimentally on an RPi 3 to maximize the chance of decoding the message from the systems I tested against. They may need to be altered for other RPi models, I haven’t tried.  I followed the principal of “being liberal in what I accept” with this code.

**Comment by bicknell** [comment]
I should have added:

If you believe there are more appropriate values I am open to patches with a description of why you think they are better values.

If I don't hear by back about the end of October, I will close this issue as answered.

Thank you for your interest!

**Comment by bicknell** [comment]
Closing with no action taken.
